[package]
name = "ltools"
version = "0.1.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ltools"
path = "src/lib.rs"

[dependencies]
clap.features = [ "cargo" ]
clap.version = "3.2.22"
nom = "7.1.1"
